module.exports = [
  [
    'vendor/notosans/notosanstc.css',
    'vendor/notosans/notosanstc.css'
  ],
  [
    'vendor/fontawesome-free-6.3.0-web/css/all.css',
    'vendor/fontawesome-free-6.3.0-web/css/all.min.css'
  ],
  [
    'vendor/overlayscrollbars@2.2.0/styles/overlayscrollbars.css',      
    'vendor/overlayscrollbars@2.2.0/styles/overlayscrollbars.min.css'
  ],
  [
    'vendor/react-reflex@4.0.9/styles.css',
    'vendor/react-reflex@4.0.9/styles.css'
  ],
  [
    'vendor/flatpickr@4.6.13/flatpickr.min.css',
    'vendor/flatpickr@4.6.13/flatpickr.min.css'
  ],
  [
    '/assets/css/flatpickr-dark-theme.css',
    '/assets/css/flatpickr-dark-theme.css'
  ],
  [
    'vendor/uppy@3.10.0/uppy.min.css',
    'vendor/uppy@3.10.0/uppy.min.css'
  ],
  [
    'vendor/select2@4.0.3/select2.css',
    'vendor/select2@4.0.3/select2.min.css'
  ],
  [
    '/assets/css/select2-light-theme.css',
    '/assets/css/select2-light-theme.css'
  ],
  [
    '/assets/css/select2-dark-theme.css',
    '/assets/css/select2-dark-theme.css'
  ],
  [
    'vendor/jsoneditor_no_worker@9.10.4/jsoneditor.min.css',
    'vendor/jsoneditor_no_worker@9.10.4/jsoneditor.min.css'
  ],

  [
    'vendor/ckeditor5/ckeditor5.development.css',
    'vendor/ckeditor5/ckeditor5.production.css'
  ]
]
